name: "Code checkes and tests"

on:
  push:
    branches: [ "master" ]

jobs:
  static-checks:
    name: Code static analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        go-version: '1.23.x'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
  
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go 1.23.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Install dependencies
      run: |
        go get .

    - name: Run tests
      run: |
        go test .